services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "8443:443"
    networks:
      - docker-network
    container_name: nginx

  mariadb:
    build:
      context: ./requirements/mariadb
    networks:
      - docker-network
    container_name: mariadb

networks:
  docker-network:
    driver: bridge
