services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "8443:443"
    networks:
      - docker-network
    depends_on:
      - wordpress
    container_name: nginx
    image: yxu/nginx:1
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ~/data/wordpress:/var/www/html
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
    networks:
      - docker-network
    container_name: mariadb
    image: yxu/mariadb:1
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    networks:
      - docker-network
    depends_on:
      - mariadb
    container_name: wordpress
    image: yxu/wordpress:1
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WP_ADMIN_PASSWD=${WP_ADMIN_PASSWD}
      - WP_USER_PASSWD=${WP_USER_PASSWD}
    volumes:
      - ~/data/wordpress:/var/www/html
    restart: unless-stopped

networks:
  docker-network:
    driver: bridge

volumes:
  db_data:
