services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "8443:443"
    networks:
      - docker-network
    container_name: nginx

  mariadb:
    build:
      context: ./requirements/mariadb
    networks:
      - docker-network
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  wordpress:
    build:
      context: ./requirements/wordpress
    networks:
      - docker-network
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}

networks:
  docker-network:
    driver: bridge
